"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react"

type Language = "vi" | "en"

type LanguageContextValue = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Common
    "common.search": "Tìm kiếm...",
    "common.light": "Sáng",
    "common.dark": "Tối",
    "common.system": "Theo hệ thống",
    "common.vietnamese": "Tiếng Việt",
    "common.english": "English",
    "common.toggleTheme": "Chuyển đổi theme",
    "common.toggleLanguage": "Chuyển đổi ngôn ngữ",
    
    // Header
    "header.myAccount": "Tài khoản của tôi",
    "header.profile": "Hồ sơ cá nhân",
    "header.switchStudent": "Chuyển học sinh",
    "header.settings": "Cài đặt",
    "header.logout": "Đăng xuất",
    "header.user": "Người dùng",
    "header.noEmail": "Chưa có email",
    "header.openMenu": "Mở menu",
    "header.closeMenu": "Đóng menu",
    
    // Settings page
    "settings.title": "Cài đặt hệ thống",
    "settings.description": "Quản lý cài đặt tài khoản, giao diện, thông báo và hệ thống.",
    "settings.appearance": "Giao diện",
    "settings.notifications": "Thông báo",
    "settings.system": "Hệ thống",
    "settings.customizeAppearance": "Tùy chỉnh giao diện",
    "settings.darkMode": "Chế độ tối",
    "settings.language": "Ngôn ngữ",
    "settings.vietnamese": "Tiếng Việt",
    "settings.english": "English",
    "settings.saveChanges": "Lưu thay đổi",
    "settings.saveSuccess": "Lưu thành công",
    "settings.saveError": "Lỗi",
    "settings.appearanceUpdated": "Cài đặt giao diện đã được cập nhật",
    "settings.notificationSettings": "Cài đặt thông báo",
    "settings.notifyDelay": "Thông báo khi xe trễ",
    "settings.notifyIncident": "Thông báo khi có sự cố",
    "settings.notificationsUpdated": "Cài đặt thông báo đã được cập nhật",
    "settings.systemSettings": "Thông số hệ thống",
    "settings.systemUpdated": "Cài đặt hệ thống đã được cập nhật và áp dụng",
    
    // Sidebar
    "sidebar.management": "Quản lý",
    "sidebar.monitoring": "Giám sát & Báo cáo",
    "sidebar.personal": "Cá nhân",
    "sidebar.overview": "Tổng quan",
    "sidebar.busManagement": "Quản lý Xe buýt",
    "sidebar.driverManagement": "Quản lý Tài xế",
    "sidebar.studentManagement": "Quản lý Học sinh",
    "sidebar.optimizeStops": "Tối ưu hóa Điểm dừng",
    "sidebar.routeManagement": "Quản lý Tuyến đường",
    "sidebar.scheduleAssignment": "Lịch trình & Phân công",
    "sidebar.realtimeTracking": "Theo dõi Real-time",
    "sidebar.notificationsAlerts": "Thông báo & Cảnh báo",
    "sidebar.reportsStatistics": "Báo cáo & Thống kê",
    "sidebar.personalProfile": "Hồ sơ cá nhân",
    "sidebar.systemSettings": "Cài đặt hệ thống",
    "sidebar.adminPanel": "Admin Panel",
    
    // Route Management
    "routes.title": "Quản lý Tuyến đường",
    "routes.description": "Quản lý và cấu hình các tuyến đường xe buýt",
    "routes.addNew": "Thêm tuyến mới",
    "routes.suggestRoute": "Đề xuất tuyến đường",
    "routes.searchPlaceholder": "Tìm kiếm tuyến đường...",
    "routes.filter": "Lọc:",
    "routes.type": "Loại:",
    "routes.all": "Tất cả",
    "routes.active": "Hoạt động",
    "routes.paused": "Tạm ngừng",
    "routes.outbound": "Tuyến đi",
    "routes.return": "Tuyến về",
    "routes.totalRoutes": "Tổng tuyến",
    "routes.activeRoutes": "Đang hoạt động",
    "routes.totalStops": "Tổng điểm dừng",
    "routes.avgTime": "Thời gian TB",
    "routes.activeStatus": "đang hoạt động",
    "routes.pausedStatus": "tạm ngừng",
    "routes.avgStops": "TB: {count} điểm/tuyến",
    "routes.estimatedCompletion": "Ước tính hoàn thành",
    "routes.stops": "điểm dừng",
    "routes.details": "Chi tiết",
    "routes.edit": "Chỉnh sửa",
    "routes.delete": "Xóa",
    "routes.roundTrip": "Cặp tuyến đi/về {count} tuyến",
    "routes.unknown": "Chưa xác định",
    "routes.noName": "Tuyến chưa có tên",
    "routes.noRoutes": "Không có tuyến đường",
    "routes.noRoutesDesc": "Bắt đầu bằng cách thêm tuyến đường đầu tiên",
    "routes.notFound": "Không tìm thấy tuyến đường",
    "routes.notFoundDesc": "Thử thay đổi bộ lọc để xem thêm tuyến đường",
    "routes.notFoundDesc2": "Bắt đầu bằng cách thêm tuyến đường đầu tiên",
    "routes.clearFilter": "Xóa bộ lọc",
    "routes.filtering": "Đang lọc:",
    "routes.status": "Trạng thái:",
    "routes.deleteConfirm": "Bạn có chắc chắn muốn xóa tuyến \"{name}\"?",
    "routes.deleteSuccess": "Đã xóa tuyến đường.",
    "routes.deleteError": "Xóa thất bại",
    "routes.loadError": "Không thể tải danh sách tuyến",
    "routes.missingStops": "Thiếu điểm dừng",
    
    // Dashboard
    "dashboard.title": "Dashboard Thống Kê",
    "dashboard.description": "Theo dõi hiệu suất và phân tích dữ liệu",
    "dashboard.filters": "Bộ lọc",
    "dashboard.fromDate": "Từ ngày",
    "dashboard.toDate": "Đến ngày",
    "dashboard.selectDate": "Chọn ngày",
    "dashboard.route": "Tuyến đường",
    "dashboard.driver": "Tài xế",
    "dashboard.bus": "Xe buýt",
    "dashboard.completionRate": "Tỷ lệ hoàn thành",
    "dashboard.avgDelay": "Trễ trung bình (P50)",
    "dashboard.delayAlerts": "Cảnh báo trễ",
    "dashboard.approachEvents": "Sự kiện đến gần",
    "dashboard.trips": "chuyến",
    "dashboard.minutes": "phút",
    "dashboard.activity": "Hoạt động",
    "dashboard.drivers": "Tài xế",
    "dashboard.buses": "xe",
    "dashboard.tripsByDay": "Chuyến theo ngày",
    "dashboard.planned": "Dự kiến",
    "dashboard.completed": "Hoàn thành",
    "dashboard.avgDelay": "Trễ TB (phút)",
    "dashboard.noData": "Không có dữ liệu",
    "dashboard.driverPerformance": "Hiệu suất tài xế",
    "dashboard.busUtilization": "Sử dụng xe buýt",
    "dashboard.routePunctuality": "Đúng giờ theo tuyến",
    "dashboard.exportReport": "Xuất báo cáo",
    "dashboard.viewFullMap": "Xem bản đồ đầy đủ",
    "dashboard.activeTrips": "Chuyến đang hoạt động",
    "dashboard.completedTrips": "Hoàn thành",
    "dashboard.delayedBuses": "Xe đang trễ",
    "dashboard.asOfToday": "Theo ngày hiện tại",
    "dashboard.incidentsToday": "Sự cố trong ngày",
    "dashboard.onTimeRate": "Tỷ lệ đúng giờ",
    "dashboard.avgMinutes": "Trung bình: {count} phút/chuyến",
    "dashboard.monitorActivity": "Theo dõi hoạt động xe buýt trong thời gian thực",
    "dashboard.weeklyPerformance": "Hiệu suất tuần này",
    "dashboard.last7Days": "7 ngày qua",
    "dashboard.busStatus": "Trạng thái xe buýt",
    "dashboard.realtimeMap": "Bản đồ theo dõi Real-time",
    "dashboard.viewFull": "Xem đầy đủ",
    "dashboard.quickStats": "Thống kê nhanh",
    "dashboard.totalBuses": "Tổng số xe",
    "dashboard.active": "Đang hoạt động",
    "dashboard.students": "Học sinh",
    "dashboard.onBus": "Đang trên xe",
    "dashboard.routes": "Tuyến đường",
    
    // Common UI
    "common.all": "Tất cả",
    "common.error": "Lỗi",
    "common.success": "Thành công",
    "common.loading": "Đang tải...",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.delete": "Xóa",
    "common.edit": "Chỉnh sửa",
    "common.add": "Thêm",
    "common.search": "Tìm kiếm...",
    "common.filter": "Lọc",
    "common.actions": "Thao tác",
    "common.status": "Trạng thái",
    "common.active": "Hoạt động",
    "common.inactive": "Tạm ngừng",
    "common.yes": "Có",
    "common.no": "Không",
    "common.confirm": "Xác nhận",
    "common.close": "Đóng",
    "common.noResults": "Không tìm thấy kết quả",
    
    // Bus Management
    "buses.title": "Quản lý Xe buýt",
    "buses.description": "Quản lý thông tin và trạng thái xe buýt",
    "buses.addNew": "Thêm xe mới",
    "buses.totalBuses": "Tổng số xe",
    "buses.active": "Đang hoạt động",
    "buses.maintenance": "Đang bảo trì",
    "buses.inactive": "Ngưng hoạt động",
    "buses.list": "Danh sách xe buýt",
    "buses.search": "Tìm kiếm...",
    "buses.status": "Trạng thái",
    "buses.allStatuses": "Tất cả trạng thái",
    "buses.sortBy": "Sắp xếp:",
    "buses.busId": "Mã xe",
    "buses.licensePlate": "Biển số",
    "buses.model": "Dòng xe",
    "buses.capacity": "Sức chứa",
    "buses.currentRoute": "Tuyến hiện tại",
    "buses.creationDate": "Ngày tạo",
    "buses.actions": "Thao tác",
    "buses.view": "Xem",
    "buses.edit": "Sửa",
    "buses.delete": "Xóa",
    "buses.unknown": "Không xác định",
    "buses.loadError": "Không lấy được danh sách xe",
    "buses.deleteConfirm": "Bạn có chắc chắn muốn xóa xe \"{name}\"?",
    "buses.deleteSuccess": "Đã xóa xe buýt",
    "buses.deleteError": "Xóa thất bại",
    "buses.ascending": "Tăng dần",
    "buses.descending": "Giảm dần",
    "buses.seats": "chỗ",
    "buses.noResults": "Không tìm thấy xe buýt nào",
    "buses.viewDetails": "Xem chi tiết",
    "buses.busCode": "Mã:",
    "buses.modelLabel": "Dòng xe:",
    "buses.capacityLabel": "Sức chứa:",
    "buses.routeLabel": "Tuyến:",
    "buses.updated": "Cập nhật:",
    "buses.clickToView": "Click để xem chi tiết",
    "buses.morningPickup": "Đón sáng",
    "buses.afternoonDropoff": "Trả chiều",
    "buses.driver": "Tài xế:",
    
    // Driver Management
    "drivers.title": "Quản lý Tài xế",
    "drivers.description": "Quản lý thông tin và phân công tài xế trong hệ thống",
    "drivers.addNew": "Thêm tài xế mới",
    "drivers.total": "Tổng tài xế",
    "drivers.working": "Đang làm việc",
    "drivers.onLeave": "Tạm nghỉ",
    "drivers.retired": "Nghỉ hưu",
    "drivers.list": "Danh sách tài xế",
    "drivers.search": "Tìm theo tên, email, số điện thoại...",
    "drivers.license": "Bằng lái:",
    "drivers.experience": "năm kinh nghiệm",
    "drivers.view": "Xem",
    "drivers.edit": "Sửa",
    "drivers.delete": "Xóa",
    "drivers.loadError": "Không lấy được danh sách tài xế",
    "drivers.deleteConfirm": "Bạn có chắc chắn muốn xóa tài xế \"{name}\"?",
    "drivers.deleteSuccess": "Đã xóa tài xế",
    "drivers.deleteError": "Xóa thất bại",
    
    // Student Management
    "students.title": "Quản lý Học sinh",
    "students.description": "Quản lý thông tin học sinh và phụ huynh",
    "students.addNew": "Thêm học sinh",
    "students.total": "Tổng học sinh",
    "students.withParent": "Có phụ huynh",
    "students.withoutParent": "Chưa có phụ huynh",
    "students.avgAge": "Tuổi trung bình",
    "students.list": "Danh sách học sinh",
    "students.search": "Tìm theo tên, lớp, phụ huynh...",
    "students.allClasses": "Tất cả lớp",
    "students.student": "Học sinh",
    "students.class": "Lớp",
    "students.birthDate": "Ngày sinh",
    "students.parent": "Phụ huynh",
    "students.address": "Địa chỉ",
    "students.status": "Trạng thái",
    "students.actions": "Thao tác",
    "students.loadError": "Không lấy được danh sách học sinh",
    "students.loadErrorDesc": "Không thể tải danh sách học sinh",
    "students.loading": "Đang tải danh sách học sinh...",
    "students.noResults": "Không tìm thấy học sinh nào",
    "students.noParent": "Chưa có",
    "students.inactive": "Ngừng hoạt động",
    "students.edit": "Chỉnh sửa học sinh",
    "students.addNewTitle": "Thêm học sinh mới",
    "students.editTitle": "Chỉnh sửa học sinh",
    
    // Optimize Stops
    "optimize.title": "Tối Ưu Hóa Điểm Dừng & Tuyến Xe",
    "optimize.description": "Sử dụng thuật toán Greedy Maximum Coverage và VRP để tối ưu hóa hệ thống",
    "optimize.complete": "Tối Ưu Hoàn Chỉnh",
    "optimize.tier1": "Tầng 1: Điểm Dừng",
    "optimize.tier2": "Tầng 2: Tuyến Xe",
    "optimize.parameters": "Tham Số",
    "optimize.parametersDesc": "Điều chỉnh tham số tối ưu hóa",
    "optimize.walkingRadius": "Bán kính đi bộ (mét)",
    "optimize.walkingRadiusDesc": "Khoảng cách tối đa học sinh đi bộ đến điểm dừng",
    "optimize.maxStudentsPerStop": "Số học sinh tối đa/điểm dừng",
    "optimize.maxStudentsPerStopDesc": "Giới hạn số học sinh tại mỗi điểm dừng",
    "optimize.busCapacity": "Sức chứa xe buýt",
    "optimize.busCapacityDesc": "Số học sinh tối đa mỗi xe buýt",
    "optimize.maxStops": "Số điểm dừng tối đa (tùy chọn)",
    "optimize.maxStopsDesc": "Để trống nếu không giới hạn",
    "optimize.noLimit": "Không giới hạn",
    "optimize.schoolLat": "Vĩ độ trường học",
    "optimize.schoolLng": "Kinh độ trường học",
    "optimize.useRoadsAPI": "Sử dụng Roads API",
    "optimize.useRoadsAPIDesc": "Snap điểm dừng lên đường lớn",
    "optimize.results": "Kết Quả",
    "optimize.noResults": "Chưa có kết quả. Nhấn \"Chạy Tối Ưu Hóa\" để bắt đầu.",
    "optimize.runOptimization": "Chạy Tối Ưu Hóa",
    
    // Schedule & Assignment
    "schedule.title": "Quản lý Lịch trình",
    "schedule.description": "Phân công và theo dõi lịch trình xe buýt",
    "schedule.addNew": "Tạo lịch trình mới",
    "schedule.total": "Tổng lịch trình",
    "schedule.applied": "Đang áp dụng",
    "schedule.morningPickup": "Đón sáng",
    "schedule.afternoonDropoff": "Trả chiều",
    "schedule.today": "Hôm nay",
    "schedule.search": "Tìm theo tuyến, xe, tài xế...",
    "schedule.all": "Tất cả",
    "schedule.reload": "Tải lại",
    "schedule.list": "Danh sách lịch trình",
    "schedule.viewTable": "Xem dạng bảng",
    "schedule.viewCalendar": "Xem theo lịch",
    "schedule.noSchedules": "Không có lịch trình nào",
    
    // Real-time Tracking
    "tracking.title": "Theo dõi Real-time",
    "tracking.description": "Giám sát vị trí và trạng thái xe buýt trực tiếp",
    "tracking.refresh": "Làm mới",
    "tracking.exportReport": "Xuất báo cáo",
    "tracking.totalVehicles": "Tổng số xe",
    "tracking.running": "Đang chạy",
    "tracking.late": "Trễ",
    "tracking.incident": "Sự cố",
    "tracking.idle": "Đứng yên",
    "tracking.avgSpeed": "Tốc độ TB",
    "tracking.students": "Học sinh",
    "tracking.search": "Tìm kiếm biển số, tuyến, tài xế...",
    "tracking.all": "Tất cả",
    "tracking.allRoutes": "Tất cả tuyến",
    "tracking.autoRefresh": "Tự động làm mới",
    "tracking.showRoutes": "Hiển thị tuyến",
    "tracking.map": "Bản đồ theo dõi",
    "tracking.mapView": "Bản đồ",
    "tracking.satellite": "Vệ tinh",
    "tracking.live": "Live",
    "tracking.autoRefresh30s": "Tự làm mới: 30s",
    "tracking.vehicles": "xe",
    "tracking.activeVehicles": "Xe đang hoạt động",
    "tracking.noVehicles": "Không tìm thấy xe nào",
    
    // Notifications & Alerts
    "notifications.title": "Thông báo & Cảnh báo",
    "notifications.description": "Theo dõi các thông báo và cảnh báo hệ thống",
    "notifications.markAllRead": "Đánh dấu tất cả đã đọc",
    "notifications.unread": "Chưa đọc",
    "notifications.warning": "Cảnh báo",
    "notifications.urgent": "Khẩn cấp",
    "notifications.success": "Thành công",
    "notifications.list": "Danh sách thông báo",
    "notifications.all": "Tất cả",
    "notifications.noNotifications": "Không có thông báo",
    "notifications.loadError": "Không thể tải thông báo",
    "notifications.markAllReadSuccess": "Đã đánh dấu tất cả đã đọc",
    "notifications.markAllReadError": "Không thể đánh dấu đã đọc",
    "notifications.deleteSuccess": "Đã xóa thông báo",
    "notifications.deleteError": "Không thể xóa thông báo",
    
    // Reports & Statistics
    "reports.title": "Báo cáo & Thống kê",
    "reports.description": "Phân tích dữ liệu và tạo báo cáo chi tiết",
    "reports.last7Days": "7 ngày qua",
    "reports.exportReport": "Xuất báo cáo",
    "reports.totalTrips": "Tổng chuyến đi",
    "reports.onTimeRate": "Tỷ lệ đúng giờ",
    "reports.students": "Học sinh",
    "reports.avgDelay": "Trễ TB",
    "reports.incidents": "Sự cố",
    "reports.activeVehicles": "Xe hoạt động",
    "reports.total": "Tổng:",
    "reports.trips": "Chuyến đi",
    "reports.buses": "Xe buýt",
    "reports.drivers": "Tài xế",
    "reports.studentsTab": "Học sinh",
    "reports.incidentsTab": "Sự cố",
    "reports.tripTrends": "Xu hướng chuyến đi",
    "reports.delayed": "Trễ",
    "reports.totalTripsChart": "Tổng chuyến",
    "reports.onTime": "Đúng giờ",
    "reports.tripDetails": "Chi tiết chuyến đi",
    "reports.onTimeTrips": "Chuyến đúng giờ",
    "reports.delayedTrips": "Chuyến trễ",
    "reports.avgTime": "Thời gian TB",
    "reports.avgDistance": "Khoảng cách TB",
    "reports.minutes": "phút",
    "reports.km": "km",
  },
  en: {
    // Common
    "common.search": "Search...",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.system": "System",
    "common.vietnamese": "Tiếng Việt",
    "common.english": "English",
    "common.toggleTheme": "Toggle theme",
    "common.toggleLanguage": "Toggle language",
    
    // Header
    "header.myAccount": "My Account",
    "header.profile": "Personal Profile",
    "header.switchStudent": "Switch Student",
    "header.settings": "Settings",
    "header.logout": "Logout",
    "header.user": "User",
    "header.noEmail": "No email",
    "header.openMenu": "Open menu",
    "header.closeMenu": "Close menu",
    
    // Settings page
    "settings.title": "System Settings",
    "settings.description": "Manage account, appearance, notification and system settings.",
    "settings.appearance": "Appearance",
    "settings.notifications": "Notifications",
    "settings.system": "System",
    "settings.customizeAppearance": "Customize Appearance",
    "settings.darkMode": "Dark Mode",
    "settings.language": "Language",
    "settings.vietnamese": "Tiếng Việt",
    "settings.english": "English",
    "settings.saveChanges": "Save Changes",
    "settings.saveSuccess": "Saved Successfully",
    "settings.saveError": "Error",
    "settings.appearanceUpdated": "Appearance settings have been updated",
    "settings.notificationSettings": "Notification Settings",
    "settings.notifyDelay": "Notify on bus delay",
    "settings.notifyIncident": "Notify on incidents",
    "settings.notificationsUpdated": "Notification settings have been updated",
    "settings.systemSettings": "System Parameters",
    "settings.systemUpdated": "System settings have been updated and applied",
    
    // Sidebar
    "sidebar.management": "Management",
    "sidebar.monitoring": "Monitoring & Reporting",
    "sidebar.personal": "Personal",
    "sidebar.overview": "Overview",
    "sidebar.busManagement": "Bus Management",
    "sidebar.driverManagement": "Driver Management",
    "sidebar.studentManagement": "Student Management",
    "sidebar.optimizeStops": "Optimize Stops",
    "sidebar.routeManagement": "Route Management",
    "sidebar.scheduleAssignment": "Schedule & Assignment",
    "sidebar.realtimeTracking": "Real-time Tracking",
    "sidebar.notificationsAlerts": "Notifications & Alerts",
    "sidebar.reportsStatistics": "Reports & Statistics",
    "sidebar.personalProfile": "Personal Profile",
    "sidebar.systemSettings": "System Settings",
    "sidebar.adminPanel": "Admin Panel",
    
    // Route Management
    "routes.title": "Route Management",
    "routes.description": "Manage and configure bus routes",
    "routes.addNew": "Add New Route",
    "routes.suggestRoute": "Suggest Route",
    "routes.searchPlaceholder": "Search routes...",
    "routes.filter": "Filter:",
    "routes.type": "Type:",
    "routes.all": "All",
    "routes.active": "Active",
    "routes.paused": "Paused",
    "routes.outbound": "Outbound",
    "routes.return": "Return",
    "routes.totalRoutes": "Total Routes",
    "routes.activeRoutes": "Active",
    "routes.totalStops": "Total Stops",
    "routes.avgTime": "Avg Time",
    "routes.activeStatus": "active",
    "routes.pausedStatus": "paused",
    "routes.avgStops": "Avg: {count} stops/route",
    "routes.estimatedCompletion": "Estimated completion",
    "routes.stops": "stops",
    "routes.details": "Details",
    "routes.edit": "Edit",
    "routes.delete": "Delete",
    "routes.roundTrip": "Round trip routes {count} routes",
    "routes.unknown": "Unknown",
    "routes.noName": "Unnamed route",
    "routes.noRoutes": "No routes",
    "routes.noRoutesDesc": "Start by adding your first route",
    "routes.notFound": "No routes found",
    "routes.notFoundDesc": "Try changing filters to see more routes",
    "routes.notFoundDesc2": "Start by adding your first route",
    "routes.clearFilter": "Clear filter",
    "routes.filtering": "Filtering:",
    "routes.status": "Status:",
    "routes.deleteConfirm": "Are you sure you want to delete route \"{name}\"?",
    "routes.deleteSuccess": "Route deleted successfully.",
    "routes.deleteError": "Delete failed",
    "routes.loadError": "Failed to load routes",
    "routes.missingStops": "Missing stops",
    
    // Dashboard
    "dashboard.title": "Statistics Dashboard",
    "dashboard.description": "Monitor performance and analyze data",
    "dashboard.filters": "Filters",
    "dashboard.fromDate": "From Date",
    "dashboard.toDate": "To Date",
    "dashboard.selectDate": "Select date",
    "dashboard.route": "Route",
    "dashboard.driver": "Driver",
    "dashboard.bus": "Bus",
    "dashboard.completionRate": "Completion Rate",
    "dashboard.avgDelay": "Avg Delay (P50)",
    "dashboard.delayAlerts": "Delay Alerts",
    "dashboard.approachEvents": "Approach events",
    "dashboard.trips": "trips",
    "dashboard.minutes": "minutes",
    "dashboard.activity": "Activity",
    "dashboard.drivers": "Drivers",
    "dashboard.buses": "buses",
    "dashboard.tripsByDay": "Trips by Day",
    "dashboard.planned": "Planned",
    "dashboard.completed": "Completed",
    "dashboard.avgDelay": "Avg Delay (min)",
    "dashboard.noData": "No data",
    "dashboard.driverPerformance": "Driver Performance",
    "dashboard.busUtilization": "Bus Utilization",
    "dashboard.routePunctuality": "Route Punctuality",
    "dashboard.exportReport": "Export Report",
    "dashboard.viewFullMap": "View Full Map",
    "dashboard.activeTrips": "Active Trips",
    "dashboard.completedTrips": "Completed",
    "dashboard.delayedBuses": "Delayed Buses",
    "dashboard.asOfToday": "As of today",
    "dashboard.incidentsToday": "Incidents Today",
    "dashboard.onTimeRate": "On-time Rate",
    "dashboard.avgMinutes": "Average: {count} min/trip",
    "dashboard.monitorActivity": "Monitor bus activity in real-time",
    "dashboard.weeklyPerformance": "This Week's Performance",
    "dashboard.last7Days": "Last 7 days",
    "dashboard.busStatus": "Bus Status",
    "dashboard.realtimeMap": "Real-time Tracking Map",
    "dashboard.viewFull": "View Full",
    "dashboard.quickStats": "Quick Stats",
    "dashboard.totalBuses": "Total Buses",
    "dashboard.active": "Active",
    "dashboard.students": "Students",
    "dashboard.onBus": "On Bus",
    "dashboard.routes": "Routes",
    "dashboard.routePunctuality": "Route Punctuality",
    "dashboard.tripCount": "Trip Count",
    "dashboard.completionRatePercent": "Completion Rate (%)",
    "dashboard.loadError": "Failed to load statistics",
    "dashboard.tryAgain": "Please try again",
    
    // Common UI
    "common.all": "All",
    "common.error": "Error",
    "common.success": "Success",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.noResults": "No results found",
    "common.tryAgain": "Please try again",
    
    // Bus Management
    "buses.title": "Bus Management",
    "buses.description": "Manage bus information and status",
    "buses.addNew": "Add New Bus",
    "buses.totalBuses": "Total Buses",
    "buses.active": "Active",
    "buses.maintenance": "In Maintenance",
    "buses.inactive": "Inactive",
    "buses.list": "Bus List",
    "buses.search": "Search...",
    "buses.status": "Status",
    "buses.allStatuses": "All Statuses",
    "buses.sortBy": "Sort by:",
    "buses.busId": "Bus ID",
    "buses.licensePlate": "License Plate",
    "buses.model": "Model",
    "buses.capacity": "Capacity",
    "buses.currentRoute": "Current Route",
    "buses.creationDate": "Creation Date",
    "buses.actions": "Actions",
    "buses.view": "View",
    "buses.edit": "Edit",
    "buses.delete": "Delete",
    "buses.unknown": "Unknown",
    "buses.loadError": "Failed to load buses",
    "buses.deleteConfirm": "Are you sure you want to delete bus \"{name}\"?",
    "buses.deleteSuccess": "Bus deleted successfully",
    "buses.deleteError": "Delete failed",
    "buses.ascending": "Ascending",
    "buses.descending": "Descending",
    "buses.seats": "seats",
    "buses.noResults": "No buses found",
    "buses.viewDetails": "View Details",
    "buses.busCode": "Code:",
    "buses.modelLabel": "Model:",
    "buses.capacityLabel": "Capacity:",
    "buses.routeLabel": "Route:",
    "buses.updated": "Updated:",
    "buses.clickToView": "Click to view details",
    "buses.morningPickup": "Morning Pickup",
    "buses.afternoonDropoff": "Afternoon Dropoff",
    "buses.driver": "Driver:",
    
    // Driver Management
    "drivers.title": "Driver Management",
    "drivers.description": "Manage driver information and assignments in the system",
    "drivers.addNew": "Add New Driver",
    "drivers.total": "Total Drivers",
    "drivers.working": "Working",
    "drivers.onLeave": "On Leave",
    "drivers.retired": "Retired",
    "drivers.list": "Driver List",
    "drivers.search": "Search by name, email, phone number...",
    "drivers.license": "License:",
    "drivers.experience": "years experience",
    "drivers.view": "View",
    "drivers.edit": "Edit",
    "drivers.delete": "Delete",
    "drivers.loadError": "Failed to load drivers",
    "drivers.deleteConfirm": "Are you sure you want to delete driver \"{name}\"?",
    "drivers.deleteSuccess": "Driver deleted successfully",
    "drivers.deleteError": "Delete failed",
    
    // Student Management
    "students.title": "Student Management",
    "students.description": "Manage student and parent information",
    "students.addNew": "Add Student",
    "students.total": "Total Students",
    "students.withParent": "With Parent",
    "students.withoutParent": "Without Parent",
    "students.avgAge": "Average Age",
    "students.list": "Student List",
    "students.search": "Search by name, class, parent...",
    "students.allClasses": "All Classes",
    "students.student": "Student",
    "students.class": "Class",
    "students.birthDate": "Date of Birth",
    "students.parent": "Parent",
    "students.address": "Address",
    "students.status": "Status",
    "students.actions": "Actions",
    "students.loadError": "Failed to load students",
    "students.loadErrorDesc": "Unable to load student list",
    "students.loading": "Loading students...",
    "students.noResults": "No students found",
    "students.noParent": "None",
    "students.inactive": "Inactive",
    "students.edit": "Edit Student",
    "students.addNewTitle": "Add New Student",
    "students.editTitle": "Edit Student",
    
    // Optimize Stops
    "optimize.title": "Optimize Stops & Routes",
    "optimize.description": "Uses Greedy Maximum Coverage and VRP algorithms to optimize the system",
    "optimize.complete": "Complete Optimization",
    "optimize.tier1": "Layer 1: Stops",
    "optimize.tier2": "Layer 2: Routes",
    "optimize.parameters": "Parameters",
    "optimize.parametersDesc": "Adjust optimization parameters",
    "optimize.walkingRadius": "Walking radius (meters)",
    "optimize.walkingRadiusDesc": "Maximum walking distance for students to stop points",
    "optimize.maxStudentsPerStop": "Maximum students/stop point",
    "optimize.maxStudentsPerStopDesc": "Limit on number of students at each stop point",
    "optimize.busCapacity": "Bus capacity",
    "optimize.busCapacityDesc": "Maximum students per bus",
    "optimize.maxStops": "Maximum stop points (optional)",
    "optimize.maxStopsDesc": "Leave blank if no limit",
    "optimize.noLimit": "No limit",
    "optimize.schoolLat": "School latitude",
    "optimize.schoolLng": "School longitude",
    "optimize.useRoadsAPI": "Use Roads API",
    "optimize.useRoadsAPIDesc": "Snap stop points to major roads",
    "optimize.results": "Results",
    "optimize.noResults": "No results yet. Click \"Run Optimization\" to start.",
    "optimize.runOptimization": "Run Optimization",
    
    // Schedule & Assignment
    "schedule.title": "Schedule Management",
    "schedule.description": "Assign and track bus schedules",
    "schedule.addNew": "Create new schedule",
    "schedule.total": "Total schedules",
    "schedule.applied": "Applied",
    "schedule.morningPickup": "Morning pickup",
    "schedule.afternoonDropoff": "Afternoon drop-off",
    "schedule.today": "Today",
    "schedule.search": "Search by route, bus, driver...",
    "schedule.all": "All",
    "schedule.reload": "Reload",
    "schedule.list": "Schedule list",
    "schedule.viewTable": "View as table",
    "schedule.viewCalendar": "View as calendar",
    "schedule.noSchedules": "No schedules found",
    
    // Real-time Tracking
    "tracking.title": "Real-time Tracking",
    "tracking.description": "Monitor the location and status of buses live",
    "tracking.refresh": "Refresh",
    "tracking.exportReport": "Export report",
    "tracking.totalVehicles": "Total vehicles",
    "tracking.running": "Running",
    "tracking.late": "Late",
    "tracking.incident": "Incident",
    "tracking.idle": "Idle",
    "tracking.avgSpeed": "Average speed",
    "tracking.students": "Students",
    "tracking.search": "Search by license plate, route, driver...",
    "tracking.all": "All",
    "tracking.allRoutes": "All routes",
    "tracking.autoRefresh": "Auto refresh",
    "tracking.showRoutes": "Show routes",
    "tracking.map": "Tracking map",
    "tracking.mapView": "Map",
    "tracking.satellite": "Satellite",
    "tracking.live": "Live",
    "tracking.autoRefresh30s": "Auto refresh: 30s",
    "tracking.vehicles": "vehicles",
    "tracking.activeVehicles": "Active vehicles",
    "tracking.noVehicles": "No vehicles found",
    
    // Notifications & Alerts
    "notifications.title": "Notifications & Alerts",
    "notifications.description": "Track system notifications and alerts",
    "notifications.markAllRead": "Mark all as read",
    "notifications.unread": "Unread",
    "notifications.warning": "Warning",
    "notifications.urgent": "Urgent",
    "notifications.success": "Success",
    "notifications.list": "Notification list",
    "notifications.all": "All",
    "notifications.noNotifications": "No notifications",
    "notifications.loadError": "Unable to load notifications",
    "notifications.markAllReadSuccess": "All notifications marked as read",
    "notifications.markAllReadError": "Unable to mark as read",
    "notifications.deleteSuccess": "Notification deleted",
    "notifications.deleteError": "Unable to delete notification",
    
    // Reports & Statistics
    "reports.title": "Reports & Statistics",
    "reports.description": "Analyze data and create detailed reports",
    "reports.last7Days": "Last 7 days",
    "reports.exportReport": "Export report",
    "reports.totalTrips": "Total trips",
    "reports.onTimeRate": "On-time rate",
    "reports.students": "Students",
    "reports.avgDelay": "Avg delay",
    "reports.incidents": "Incidents",
    "reports.activeVehicles": "Active vehicles",
    "reports.total": "Total:",
    "reports.trips": "Trips",
    "reports.buses": "Buses",
    "reports.drivers": "Drivers",
    "reports.studentsTab": "Students",
    "reports.incidentsTab": "Incidents",
    "reports.tripTrends": "Trip Trends",
    "reports.delayed": "Delayed",
    "reports.totalTripsChart": "Total trips",
    "reports.onTime": "On-time",
    "reports.tripDetails": "Trip Details",
    "reports.onTimeTrips": "On-time trips",
    "reports.delayedTrips": "Delayed trips",
    "reports.avgTime": "Average time",
    "reports.avgDistance": "Average distance",
    "reports.minutes": "minutes",
    "reports.km": "km",
  },
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("vi")

  // Load language from localStorage on mount
  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("ssb_language")
      if (saved === "vi" || saved === "en") {
        setLanguageState(saved)
      }
    }
  }, [])

  // Update html lang attribute
  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language
    }
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== "undefined") {
      localStorage.setItem("ssb_language", lang)
    }
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
      })
    }
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

